AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  short-url

  Sample SAM Template for short-url

Globals:
  Function:
    Timeout: 3
    LoggingConfig:
      LogFormat: JSON

Resources:
  DynamoURLShortenerTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: URLShortener
      AttributeDefinitions:
        - AttributeName: alias
          AttributeType: S
        - AttributeName: access_count
          AttributeType: N
      KeySchema:
        - AttributeName: alias
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      GlobalSecondaryIndexes:
        - IndexName: AccessCountIndex
          KeySchema:
            - AttributeName: access_count
              KeyType: HASH
            - AttributeName: alias
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5

  CreateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/
      Handler: api/create.lambdaHandler
      Runtime: nodejs18.x
      Policies: 
        - DynamoDBCrudPolicy:
            TableName: 'URLShortener'
      Environment:
        Variables:
          TABLE_NAME: 'URLShortener'
      Architectures:
      - x86_64
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /urls
            Method: post
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
        - api/create.ts

Outputs:
  BaseAPIURL:
    Description: API Gateway endpoint URL for Prod stage
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
